[package]
name = "kerrex-gdnative-sys"
version = "0.1.3"
authors = ["Kerrex <romen3@gmail.com>"]
description = "Bindings to the GDNative C API"
repository = "https://github.com/Kerrex/godot-rust"
license = "MIT"

[lib]
name = "gdnative_sys"
crate-type = ["dylib"]

[dependencies]
